version: "3"
services:
  core:
    build: ./Santa
    ports:
      - "5000:80"
    depends_on:
      - db
    restart: always
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Sapass9@'
    volumes:
      - "dbdata:/var/opt/mssql/data"

volumes:
  dbdata: